# Generated by Django 4.1.4 on 2022-12-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='block_call',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='block_email',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='block_sms',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=44, unique=True),
        ),
    ]
