# Generated by Django 4.1.4 on 2022-12-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_block_call_alter_profile_block_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='block_call',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='block_email',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='block_sms',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
